original_repo: https://github.com/hackcu/localhackday

volunteer_mentor_form: "https://forms.gle/CczF94ZWjidGAVou9"
live_page: "https://live.hackcu.org/"
register: "https://localhackday.mlh.io/build/locations/2419"

description: "Join us for Local Hack Day on December 7, 2019 at the University of Colorado Boulder."
title: Local Hack Day 2019
og_image: https://phase.hackcu.org/assets/images/ogimage870x450.png

sass:
    sass_dir: assets/_sass
    style: compressed